-- 20260401000001_create_games.sql
-- Migrated from ddl/002_create_games.sql
CREATE TABLE IF NOT EXISTS public.games (
  id BIGSERIAL PRIMARY KEY,
  date DATE,
  game_type VARCHAR(2) NOT NULL CHECK (game_type IN ('3p','4p')),
  player_count SMALLINT NOT NULL DEFAULT 4,
  player1 TEXT,
  player2 TEXT,
  player3 TEXT,
  player4 TEXT,
  score1 INTEGER,
  score2 INTEGER,
  score3 INTEGER,
  score4 INTEGER,
  rank1 SMALLINT,
  rank2 SMALLINT,
  rank3 SMALLINT,
  rank4 SMALLINT,
  is_tobi1 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobi2 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobi3 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobi4 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobashi1 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobashi2 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobashi3 BOOLEAN NOT NULL DEFAULT FALSE,
  is_tobashi4 BOOLEAN NOT NULL DEFAULT FALSE,
  is_yakitori1 BOOLEAN NOT NULL DEFAULT FALSE,
  is_yakitori2 BOOLEAN NOT NULL DEFAULT FALSE,
  is_yakitori3 BOOLEAN NOT NULL DEFAULT FALSE,
  is_yakitori4 BOOLEAN NOT NULL DEFAULT FALSE,
  score_total INTEGER,
  top_player TEXT,
  last_player TEXT,
  tobi_player TEXT,
  tobashi_player TEXT,
  yakitori_players TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_games_date_created_at ON public.games (date DESC, created_at DESC);
